# Numpy-Datentypen
  
- Numpy arbeitet mit Fixed-Type Arrays, was es besonders effizient gegenüber klassischen Python-Listen macht
- Der Numpy-Datentyp kann mittels Attribute `.dtype` abgefragt werden


In [1]:
# Datentyp "dtype" abgefragen
import numpy as np

array2 = np.random.random((3, 3)) 
print("dtype:  ",array2.dtype)


dtype:   float64


In [2]:
# Bei der Konstruktion eines Arrays kann der dtype angegeben werden

# Es gibt verschiedene Schreibweisen
np.zeros(10, dtype='int16') # Hier als String
np.zeros(10, dtype=np.int16) # Als Type


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

## Standard Numpy Datentypen:

```text

    Data type 	Description
      
    bool_ 	Boolean (True or False) stored as a byte
    int_ 	Default integer type (same as C long; normally either int64 or int32)
    intc 	Identical to C int (normally int32 or int64)
    intp 	Integer used for indexing (same as C ssize_t; normally either int32 or int64)
    int8 	Byte (-128 to 127)
    int16 	Integer (-32768 to 32767)
    int32 	Integer (-2147483648 to 2147483647)
    int64 	Integer (-9223372036854775808 to 9223372036854775807)
    uint8 	Unsigned integer (0 to 255)
    uint16 	Unsigned integer (0 to 65535)
    uint32 	Unsigned integer (0 to 4294967295)
    uint64 	Unsigned integer (0 to 18446744073709551615)
    float_ 	Shorthand for float64.
    float16 	Half precision float: sign bit, 5 bits exponent, 10 bits mantissa
    float32 	Single precision float: sign bit, 8 bits exponent, 23 bits mantissa
    float64 	Double precision float: sign bit, 11 bits exponent, 52 bits mantissa
    complex_ 	Shorthand for complex128.
    complex64 	Complex number, represented by two 32-bit floats
    complex128 	Complex number, represented by two 64-bit floats
```

## dtype-Kürzel/Kurzschreibweisen
<ul>
<li><code class="w3-codespan">i</code> - integer</li>
<li><code class="w3-codespan">b</code> - boolean</li>
<li><code class="w3-codespan">u</code> - unsigned integer</li>
<li><code class="w3-codespan">f</code> - float</li>
<li><code class="w3-codespan">c</code> - complex float</li>
<li><code class="w3-codespan">m</code> - timedelta</li>
<li><code class="w3-codespan">M</code> - datetime</li>
<li><code class="w3-codespan">O</code> - object</li>
<li><code class="w3-codespan">S</code> - string</li>
<li><code class="w3-codespan">U</code> - unicode string</li>
<li><code class="w3-codespan">V</code> - fixed chunk of memory for other type ( void )</li>
</ul>

In [ ]:
np.zeros(10, dtype=np.dtype('i2')) # Kürzel i2 = Integer aus 2 Byte = 16bit
np.zeros(10, dtype=np.dtype('i4')) # Kürzel i2 = Integer aus 4 Byte = 32bit
np.zeros(10, dtype=np.dtype('f4')) # Kürzel f4 = float32
np.zeros(10, dtype='f4')

arr = np.array(['apple', 'banana', 'cherrys'])
print(arr.dtype) # <U7 = Unicode aus 7 Byte = 7 Zeichen

arr = np.array([11, 2, 3, 4], dtype='S')
print(arr.dtype) # |S2 = String, 2 Byte (wegen '11')


date_arr = np.array(['2007-07-13', '2006-01-13', '2010-08-13'], dtype=np.datetime64)
print(date_arr.dtype) # datetime64[D]

date_arr2 = np.array(['2001-01-01T12:00', '2002-02-03T13:56:03.172','2002-02-03T13:56:03.172'], dtype=np.datetime64)
print(date_arr2.dtype) # datetime64[ms]

(date_arr- date_arr2).dtype # <m8[ms] 


<U7
|S2
datetime64[D]
datetime64[ms]


dtype('<m8[ms]')

#### Datentyp Konvertieren mit `.astype()`

In [4]:
# Datentyp Konvertieren mit `.astype()`

np.zeros(10, dtype=np.dtype('f4')).astype('i') # Konvertieren
#np.zeros(10, dtype=np.dtype('f4')).astype(np.int32) 
#np.zeros(10, dtype=np.dtype('i4')).astype(np.float32) 
#np.zeros(10, dtype=np.dtype('i4')).astype(bool) # bool

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [10]:
np.zeros((4,3), dtype=np.int16) # Mehrdimensionale Arrays

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int16)

### Irrationalen Zahlen und Complexen Zahlen 

* <https://www.youtube.com/watch?v=P24tmohytXs>
* <https://www.youtube.com/watch?v=sF5kIWCq3D8>


## NaN - "not a Number" 

* "In der Informationstechnik steht NaN (englisch für „Not a Number“ – „Keine Zahl“) für einen numerischen Datentyp-Wert, der einem undefinierten oder nicht darstellbaren Wert entspricht, und kommt insbesondere bei Gleitkommazahlberechnungen vor."

* es kann immer mal vorkommen das Datensätze unvollständig sind, dann sind unter Umständen einige Element mit NaN initialisiert

In [18]:
# NaN / not a number

import numpy as np

# nan-Value "explizit" in einem Numpy-Array
x = np.array([3.14, np.nan, 2.2, 3.1]) #

# nan-Value entsteht beim Import von csv-Daten, wenn 
data = np.genfromtxt('csv/matrix2.csv', delimiter=',')

print(x)
print("----")
print(data)


[3.14  nan 2.2  3.1 ]
----
[[ 1.  2.  3.  4.  5.]
 [ 6. nan  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]]


### ***NaN***-Werte können zu unerwarteten oder unerwünschten Ergebnissen führen

In [15]:
print("Minimum des Array: ",np.min(data))

Minimum des Array:  nan


#### Möglichkeiten mit NaN-Werten zu arbeiten
* Prüfen auf NaN: np.isnan(x)
* filling_values=0 parameter bei laden des csv: np.genfromtxt('data/src/sample_nan.csv', delimiter=',', filling_values=0)
* Ersetzen der NaN mit einem anderen Wert z.B. mit np.where()
* `np.nan_to_num()`

In [22]:
# 
data = np.genfromtxt('csv/matrix2.csv', delimiter=',')

print(data)
print("-------")

data2 = np.nan_to_num(data) # Setzt 0.0 statt NaN
#np.nan_to_num(data, copy=False) # copy=True ist default
print(data2)

print("-------")
data2 = np.where(np.isnan(data),0.1,data) # 
#data2 = np.genfromtxt('csv/matrix2.csv', delimiter=',', filling_values=100)
print(data2)





[[ 1.  2.  3.  4.  5.]
 [ 6. nan  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]]
-------
[[ 1.  2.  3.  4.  5.]
 [ 6.  0.  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]]
-------
[[ 1.   2.   3.   4.   5. ]
 [ 6.   0.1  8.   9.  10. ]
 [11.  12.  13.  14.  15. ]
 [16.  17.  18.  19.  20. ]]
