# Array Indexing & Slicing: 

### Indexing und Slicing bei 1 dimensionalen Arrays

In [8]:
import numpy as np

x = np.array([1,2,3,4,5,6])
type(x)

#indexing
print(x[0])
print(x[-1]) # negative indices sind erlaubt

#slicing
print(x[0:2]) # [1 2]
print(x[0:5:2],type(x[0:5:2]))


x = np.array([[1,2,3],[4,5,6]])
print(x[0][0])


1
6
[1 2]
[1 3 5] <class 'numpy.ndarray'>
1


### Indexing bei Mehrdimensionalen Arrays

- Beim Indexing ist der "End-Index" INCLUSIVE aber NICHT bei SLICING (',') !!
- Beim Indexing von mehrdimensionalen Arrays

In [ ]:
np.random.seed(42)
A = np.random.randint(0,100,(6,6))
print(A)

#Indexing
print(A[2,2]) # Index beginnt mit 0, 2 inclusive
print(A[-1,-1]) 



[[51 92 14 71 60 20]
 [82 86 74 74 87 99]
 [23  2 21 52  1 87]
 [29 37  1 63 59 20]
 [32 75 57 21 88 48]
 [90 58 41 91 59 79]]
21
79


#### Slicing bei Mehrdimensionalen Arrays:
  
- Dimensionen werden in der "Eckige-Klammer"-Syntax mit Komma separiert : 
  
<img src="img/array-slicing.png" width="25%" style="margin-left:0px;"/>

##### Warum resultieren die Arrays in unterschiedlichen Shapes?
___Gemini___:  
"Der Hauptunterschied besteht darin, dass beim  _Slicing_ die Dimensionen des Arrays <u>erhalten</u> bleiben, während sie durch "Indexing" <u>reduziert</u> werden können. 


#### Beispiel

In [25]:
A = np.arange(9).reshape((3,3))
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [29]:
#Beispiel: 
#a)
A[2] # 
A[2].shape
A[2].ndim

#b)
A[2:,:] 
A[2:,:].shape
#A[2:,:].ndim


A[2],A[2:,:] 


(array([6, 7, 8]), array([[6, 7, 8]]))

<br>
<img src="img/axis-dimensions.png" width="400"/>

#### Was ist der Unterschied? 

__(3,) Shape: 1-Dimensional Array__

Ein Array mit der Shape (3,) ist ein __1-dimensionales array__, auch Spalten-Vektor genannt. Es hat eine Axe 0 mit der Länge 3. 
Man kann es sich als Liste von  Zahlen vorstellen.

__(1, 3) Shape: 2-Dimensional Array__

Ein Array der Shape (1, 3) ist ein __2-dimensional array__, auch Matrix genannt. Es hat zwei Achsen:

- Axis 0 (rows): der Länge 1.

- Axis 1 (columns): der Länge 3.

Man kannn es sich als Tabelle mit einer Zeile und drei Spalten vorstellen.

___Zusammenfassend lässt sich sagen, dass ein (3,) Array ein eindimensionaler Vektor ist, während ein (1,3) Array eine zweidimensionale Matrix ist.___

#### Ist dieser Unterschied wichtig?

In manchen Situationen: 

- manche Framworks/ Algorithmen brauchen eine bestimmte Shape. (bsp.: `scikit-learn` )


- Es macht einen Unterschied bei der Matrizenmultiplikation (`np.dot` oder `@`):

    - Die Multiplikation eines (1,3)-Arrays mit einem (3,1)-Array ist möglich und ergibt eine Matrix der Shape (1,1).

    - Die Multiplikation eines (3,)-Arrays mit einem (3,)-Array ist als Matrizenmultiplikation nicht definiert, da die Dimensionen nicht kompatibel sind. Stattdessen führt np.dot(v, v) eine Punktprodukt-Operation durch und gibt einen Skalar der Shape "()" zurück.



### Slicing mit 2-Dimensionalen-Arrays, - also "Matrizen"

In [ ]:
import numpy as np


In [ ]:
#Beispiele:
print("-------")



In [ ]:
print("-------")


In [ ]:

#print(type(A))

print("-------")



#### 3d-Array Slicing/Indexing

## Boolean Indexing / Masking
  
- Boolen Indexing kann verwendet werden um eine Matrix zu "Filtern"

In [ ]:
# Elementweiser Vergleich 



In [ ]:
# Boolean Indexing  + Slicing


In [ ]:

# Masking mit &,|,~


### Array Manipulation

In [ ]:
# Daten können auf diese Weise auch manipuliert werden:
data = np.array([(4,7),(0,2),(-5,6),(0,0)])

print(data)
print("----")



## Fancy Indexing

Indexing mit Integer-Arrays

In [ ]:
print(arr)


In [ ]:
 # Verkettung möglich  

In [ ]:
 # Verkettung möglich  

### Achtung: 
Beim Slicing mit NumPy werden im Gegensatz zu Standard-Python-Slicing <u>keine Kopien erzeugt</u>, stattdessen spricht man von __Views__

- Basic Indexing und Slicing erzeugt Views

#### Basic Indexing 

In [ ]:
# Basic Indexing erzeugt view


### Advanced Indexing erzeugt eine Kopie

- "Fancy"-Indexing
- Boolean-Indexing

In [ ]:
print("-- Fancy-Indexing:")


In [ ]:
print("-- Boolean-Indexing:")

### Arrays Verknüpfen 
- `concat()`
- `vstack()`
- `hstack`

In [ ]:
#concat 1

In [ ]:
#concat 2


In [ ]:
#concat 3


In [ ]:
# hstack, vstack