# Array Indexing & Slicing: 

### Indexing und Slicing bei 1 dimensionalen Arrays

In [2]:
import numpy as np

x = np.array([5, 0, 3, 4, 7, 9])
print(type(x))

#indexing
print("x[0]: ",x[0])
print("x[3]: ",x[3])
print("x[-1]: ",x[-1]) # negative indices sind erlaubt !

#slicing
print("x[0:2]: ",x[0:2],type(x)) # teil_array[von:bis_exclusive]
print("x[0:5:2]: ",x[0:5:2],type(x))



<class 'numpy.ndarray'>
x[0]:  5
x[3]:  4
x[-1]:  9
x[0:2]:  [5 0] <class 'numpy.ndarray'>
x[0:5:2]:  [5 3 7] <class 'numpy.ndarray'>


### Indexing bei Mehrdimensionalen Arrays

- Beim Indexing ist der "End-Index" INCLUSIVE aber NICHT bei SLICING (',') !!
- Beim Indexing von mehrdimensionalen Arrays

In [ ]:

np.random.seed(42) # Reproduzierbare Ergebnisse
A = np.random.randint(0, 100, (6, 6))

print(A)

#Indexing:
print("A[0,3]: ",A[0,3])# Index beginnt bei 0, - 3 inklusive
print("A[2,3]: ",A[2,3]) # 3 inklusive => End-Index inklusive !
print("A[2,-1]: ",A[2,-1]) # -1 inklusive



[[51 92 14 71 60 20]
 [82 86 74 74 87 99]
 [23  2 21 52  1 87]
 [29 37  1 63 59 20]
 [32 75 57 21 88 48]
 [90 58 41 91 59 79]]
A[0,3]:  71
A[2,3]:  52
A[2,-1]:  87


#### Slicing bei Mehrdimensionalen Arrays:
  
- Dimensionen werden in der "Eckige-Klammer"-Syntax mit Komma separiert : 
  
<img src="img/array-slicing.png" width="25%" style="margin-left:0px;"/>

##### Warum resultieren die Arrays in unterschiedlichen Shapes?
___Gemini___:  
"Der Hauptunterschied besteht darin, dass beim  _Slicing_ die Dimensionen des Arrays <u>erhalten</u> bleiben, während sie durch "Indexing" <u>reduziert</u> werden können. 


#### Beispiel

In [24]:
#Beispiel: 
A = np.arange(9).reshape((3,3))

A
#A[2] # array([6, 7, 8]) 
#A[2].shape
#A[2].ndim

#b)

A[2:,:] # array([[6, 7, 8]])
#A[2:,:].shape # (1, 3)
#A[2:,:].ndim


B = A[2:,:].reshape((3,))
B
#B.shape



array([6, 7, 8])

<br>
<img src="img/axis-dimensions.png" width="400"/>

#### Was ist der Unterschied? 

__(3,) Shape: 1-Dimensional Array__

Ein Array mit der Shape (3,) ist ein __1-dimensionales array__, auch Spalten-Vektor genannt. Es hat eine Axe 0 mit der Länge 3. 
Man kann es sich als Liste von  Zahlen vorstellen.

__(1, 3) Shape: 2-Dimensional Array__

Ein Array der Shape (1, 3) ist ein __2-dimensional array__, auch Matrix genannt. Es hat zwei Achsen:

- Axis 0 (rows): der Länge 1.

- Axis 1 (columns): der Länge 3.

Man kannn es sich als Tabelle mit einer Zeile und drei Spalten vorstellen.

___Zusammenfassend lässt sich sagen, dass ein (3,) Array ein eindimensionaler Vektor ist, während ein (1,3) Array eine zweidimensionale Matrix ist.___

#### Ist dieser Unterschied wichtig?

In manchen Situationen: 

- manche Framworks/ Algorithmen brauchen eine bestimmte Shape. (bsp.: `scikit-learn` )


- Es macht einen Unterschied bei der Matrizenmultiplikation (`np.dot` oder `@`):

    - Die Multiplikation eines (1,3)-Arrays mit einem (3,1)-Array ist möglich und ergibt eine Matrix der Shape (1,1).

    - Die Multiplikation eines (3,)-Arrays mit einem (3,)-Array ist als Matrizenmultiplikation nicht definiert, da die Dimensionen nicht kompatibel sind. Stattdessen führt np.dot(v, v) eine Punktprodukt-Operation durch und gibt einen Skalar der Shape "()" zurück.



### Slicing mit 2-Dimensionalen-Arrays, - also "Matrizen"

In [2]:
import numpy as np

np.random.seed(42)
A = np.random.randint(0, 100, (6, 6))

print(A)

[[51 92 14 71 60 20]
 [82 86 74 74 87 99]
 [23  2 21 52  1 87]
 [29 37  1 63 59 20]
 [32 75 57 21 88 48]
 [90 58 41 91 59 79]]


In [78]:
#Beispiele:
print("-------")
print("A[0:2,2:4]: ",A[0:2,2:4],sep="\n") # Zeile 0 und 1 verknüpft mit Spalte 2 & 3  


-------
A[0:2,2:4]: 
[[14 71]
 [74 74]]


In [79]:
print("-------")
print("A[0:6,2:4]: ",A[0:6,2:4],sep="\n") 

-------
A[0:6,2:4]: 
[[14 71]
 [74 74]
 [21 52]
 [ 1 63]
 [57 21]
 [41 91]]


In [3]:

#print(type(A))

print("-------")
print("A[:2,:3]: ",A[:2,:3],sep="\n") 


-------
A[:2,:3]: 
[[51 92 14]
 [82 86 74]]


#### 3d-Array Slicing/Indexing

In [81]:

arr_3d =  np.arange(1,9).reshape((2,2,2))
print(arr_3d)
print("-----")
print(arr_3d[0,:,:])
#[[1 2]
# [3 4]]

print("-----")
print(arr_3d[0,1,:])
#[3 4]

print("-----")
print(arr_3d[:,0,1])
#[2 6]

# 4d ?


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
-----
[[1 2]
 [3 4]]
-----
[3 4]
-----
[2 6]


## Boolean Indexing / Masking
  
- Boolen Indexing kann verwendet werden um eine Matrix zu "Filtern"

In [4]:
names = np.array(['bob','joe','will','bob'])


In [8]:
# Elementweiser Vergleich 
bool_arr = (names == 'bob')
bool_arr


array([ True, False, False,  True])

In [9]:
data = np.array([(4,7),(0,2),(-5,6),(0,0)]) # Liste von 
print(data.shape)
data

(4, 2)


array([[ 4,  7],
       [ 0,  2],
       [-5,  6],
       [ 0,  0]])

In [10]:
data[bool_arr]

#data[names == 'bob'] # Einzeiler 
# array([[4, 7],
#        [0, 0]])


array([[4, 7],
       [0, 0]])

In [12]:
# Boolean Indexing  + Slicing
data[names == 'bob',1:]


array([[7],
       [0]])

In [ ]:

# Masking mit &,|,~
print(names)

~(names == 'bob') # <=> NOT , NICHT wie mit Python-Booleans: and, or, not sondern &,|,

mask = (names == 'bob') | (names == 'will') # &,|,
mask

['bob' 'joe' 'will' 'bob']


array([ True, False,  True,  True])

### Array Manipulation

In [88]:
# Daten können auf diese Weise auch manipuliert werden:
data = np.array([(4,7),(0,2),(-5,6),(0,0)])

print(data)
print("----")

data[data < 0] = 0 # 
print(data)

print("----")
print(data[names != 'joe'])
print("----")
data[names != 'joe'] = 7
print(data)

[[ 4  7]
 [ 0  2]
 [-5  6]
 [ 0  0]]
----
[[4 7]
 [0 2]
 [0 6]
 [0 0]]
----
[[4 7]
 [0 6]
 [0 0]]
----
[[7 7]
 [0 2]
 [7 7]
 [7 7]]


## Fancy Indexing

Indexing mit Integer-Arrays

In [89]:
arr = np.arange(8*4).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [90]:
arr[[4,3,0,-2]] # => Zeilen-Index: 4,3,0,-2

array([[16, 17, 18, 19],
       [12, 13, 14, 15],
       [ 0,  1,  2,  3],
       [24, 25, 26, 27]])

In [91]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [92]:
print(arr)
arr[[4,3,0,-2],[0,1,2,0]] 

# Zeilen 4 und Spalte 0 = 16
# Zeile 3 und Spalte 1 = 13
# Zeile 0 und Spalte 2 = 2
# Zeile -2 und Spalte 0 = 24

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


array([16, 13,  2, 24])

In [93]:
arr[[4,3,0,-2],[0,1,2,3]][:2] # Verkettung möglich  

array([16, 13])

In [94]:
arr[[4,3,0,-2],[0,1,2,3]][:2][0] # Verkettung möglich  

np.int64(16)

### Achtung: 
Beim Slicing mit NumPy werden im Gegensatz zu Standard-Python-Slicing <u>keine Kopien erzeugt</u>, stattdessen spricht man von __Views__

- Basic Slicing/Indexing erzeugt Views 


In [14]:
arr = np.arange(9).reshape((3,3))

print(arr)
print("----")
view = arr[:2,:]
print(view)
view[0,0] = -1
print(arr) # (!)

print("------")
# Möchte man eine Kopie erzeugen kann man .copy() verwenden
arr = np.arange(9).reshape((3,3))
my_copy = arr[:2,:].copy()
print(my_copy)
my_copy[0,0] = -2
print(arr)




[[0 1 2]
 [3 4 5]
 [6 7 8]]
----
[[0 1 2]
 [3 4 5]]
[[-1  1  2]
 [ 3  4  5]
 [ 6  7  8]]
------
[[0 1 2]
 [3 4 5]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Basic Indexing erzeugt einen View

In [8]:
# Indexing gerzeugt eine Kopie
print("-- Indexing:")
arr = np.arange(9).reshape((3,3))
print(arr)
no_view = arr[1]
no_view[0] = -1
print("----")
print(no_view)
print("----")
print(arr)


-- Indexing:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
----
[-1  4  5]
----
[[ 0  1  2]
 [-1  4  5]
 [ 6  7  8]]


### Advanced Indexing erzeugt eine Kopie

- "Fancy"-Indexing
- Boolean-Indexing

In [9]:
print("-- Fancy-Indexing:")
arr = np.arange(9).reshape((3,3))
print(arr)
print("------")
no_view = arr[[0,1,2]]
no_view[0,0] = -1
print(no_view)
print("------")
print(arr)



-- Fancy-Indexing:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
------
[[-1  1  2]
 [ 3  4  5]
 [ 6  7  8]]
------
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [15]:
print("-- Boolean-Indexing:")
arr = np.arange(9).reshape((3,3))
print(arr)
tmp = arr[(arr > 4)]
tmp[0] = 100
print(tmp)
print(arr)



-- Boolean-Indexing:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[100   6   7   8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


### Arrays Verknüpfen 
- `concat()`
- `vstack()`
- `hstack`

In [18]:
A = np.concat([np.arange(3),np.arange(3)])


A

array([0, 1, 2, 0, 1, 2])

In [19]:
A = np.arange(9).reshape((3,3))
B = np.concat([A,A])
B

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [20]:
C = np.concat([A,A],axis=1)
C

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [101]:
D = np.vstack([A,A])
E = np.hstack([A,A])

D,E

(array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8],
        [0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 array([[0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5],
        [6, 7, 8, 6, 7, 8]]))