## Numpy-Arrays in eine Datei schreiben und lesen

In [2]:

import numpy as np

#Array in Datei schreiben
arr = np.arange(20).reshape((4,5))

np.save('data/myarray.npy',arr) 



In [3]:
#Array in Datei lesen
arr_loaded = np.load('data/myarray.npy')
print(arr_loaded)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [4]:

# Array Archiv (uncompressed) ".npz"
arr1 = np.arange(20).reshape((4,5))
arr2 = np.arange(20).reshape((2,5,2))

np.savez('data/array_archive.npz', first=arr, second=arr2, third=arr1) # **kwargs

arch = np.load('data/array_archive.npz')
print("---")
print('second:\n',arch['second'])
print('third:\n',arch['third'])

---
second:
 [[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]
third:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
